/*package com.sample.rules
 
dialect "mvel"

import com.sample.model.Customer;
import java.util.Date
import java.sql.Connection
import java.sql.DriverManager
import java.sql.ResultSet
import java.sql.Statement


function String ConnectDB(String ConnectionClass,String url,String user, String password) {
 
    Class.forName(ConnectionClass);
    java.sql.Connection con = DriverManager.getConnection(url, user, password);
    Statement st = con.createStatement();
    ResultSet rs = st.executeQuery("select * from test.Customer where id=1");
    rs.first();
  return rs.getString("name");
        
}

   
rule "DBConnection"
 when
      customer:Customer(name == ConnectDB("com.mysql.cj.jdbc.Driver","jdbc:mysql://localhost:3306/test","root","Deba2021!"))
 then
   System.out.println("Database call done. Rule executed");
 end
*/