package com.sample.model;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShoppingCart implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double cartTotal;
	private java.lang.Double cartItemTotal;
	private java.lang.Double shippingTotal;
	private java.lang.Double cartItemPromoSavings;
	private java.lang.Double shippingPromoSavings;

	public ShoppingCart() {
	}

	public java.lang.Double getCartTotal() {
		return this.cartTotal;
	}

	public void setCartTotal(java.lang.Double cartTotal) {
		this.cartTotal = cartTotal;
	}

	public java.lang.Double getCartItemTotal() {
		return this.cartItemTotal;
	}

	public void setCartItemTotal(java.lang.Double cartItemTotal) {
		this.cartItemTotal = cartItemTotal;
	}

	public java.lang.Double getShippingTotal() {
		return this.shippingTotal;
	}

	public void setShippingTotal(java.lang.Double shippingTotal) {
		this.shippingTotal = shippingTotal;
	}

	public java.lang.Double getCartItemPromoSavings() {
		return this.cartItemPromoSavings;
	}

	public void setCartItemPromoSavings(java.lang.Double cartItemPromoSavings) {
		this.cartItemPromoSavings = cartItemPromoSavings;
	}

	public java.lang.Double getShippingPromoSavings() {
		return this.shippingPromoSavings;
	}

	public void setShippingPromoSavings(java.lang.Double shippingPromoSavings) {
		this.shippingPromoSavings = shippingPromoSavings;
	}

	public ShoppingCart(java.lang.Double cartTotal,
			java.lang.Double cartItemTotal, java.lang.Double shippingTotal,
			java.lang.Double cartItemPromoSavings,
			java.lang.Double shippingPromoSavings) {
		this.cartTotal = cartTotal;
		this.cartItemTotal = cartItemTotal;
		this.shippingTotal = shippingTotal;
		this.cartItemPromoSavings = cartItemPromoSavings;
		this.shippingPromoSavings = shippingPromoSavings;
	}

	@Override
	public String toString() {
		return "ShoppingCart [cartTotal=" + cartTotal + ", cartItemTotal=" + cartItemTotal + ", shippingTotal="
				+ shippingTotal + ", cartItemPromoSavings=" + cartItemPromoSavings + ", shippingPromoSavings="
				+ shippingPromoSavings + "]";
	}
	
	

}